# Generated by Django 3.0.3 on 2020-02-11 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bd_account_fb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bm_account', models.URLField()),
                ('rec_account', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='bd_other_fb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('other_proxy', models.URLField()),
                ('other_bankcard', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='bd_photoshop_fb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photoshop_ooo', models.URLField()),
                ('photoshop_ip', models.URLField()),
                ('photoshop_oficce', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='bd_promocode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company1', models.CharField(max_length=128)),
            ],
        ),
    ]
