# Generated by Django 3.0.3 on 2020-02-23 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='db_common',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=128)),
                ('url', models.URLField(unique=True)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('stock', models.PositiveIntegerField(verbose_name='На складе')),
                ('available', models.BooleanField(default=True, verbose_name='Доступен')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
                'index_together': {('id', 'slug')},
            },
        ),
        migrations.DeleteModel(
            name='bd_account_fb',
        ),
        migrations.DeleteModel(
            name='bd_other_fb',
        ),
        migrations.DeleteModel(
            name='bd_photoshop_fb',
        ),
        migrations.DeleteModel(
            name='bd_promocode',
        ),
    ]
