# Generated by Django 3.0.3 on 2020-02-23 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20200223_0004'),
    ]

    operations = [
        migrations.AddField(
            model_name='db_common',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1500, max_digits=10, verbose_name='Цена'),
            preserve_default=False,
        ),
    ]
