# Generated by Django 3.0.3 on 2020-02-23 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        ('shop', '0003_db_common_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Категория', models.CharField(max_length=128, unique=True)),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('available', models.BooleanField(default=True, verbose_name='Существует')),
                ('slug', models.SlugField(max_length=200, unique=True)),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['name'],
            },
        ),
        migrations.RenameModel(
            old_name='db_common',
            new_name='Product',
        ),
    ]
