# Generated by Django 2.2.10 on 2020-02-23 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_product_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='url',
        ),
    ]
