# Generated by Django 2.2.10 on 2020-02-24 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_remove_product_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='modal',
            field=models.CharField(default=10, max_length=128),
            preserve_default=False,
        ),
    ]
