# Generated by Django 2.2.10 on 2020-02-26 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        ('shop', '0008_product_modal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category_offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Категория', models.CharField(max_length=128, unique=True)),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('available', models.BooleanField(default=True, verbose_name='Существует')),
                ('slug', models.SlugField(max_length=200, unique=True)),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['name'],
            },
        ),
        migrations.RenameModel(
            old_name='Product',
            new_name='Product_fb',
        ),
        migrations.RenameModel(
            old_name='Category',
            new_name='Category_fb',
        ),
        migrations.CreateModel(
            name='Product_offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=128)),
                ('modal', models.CharField(max_length=128)),
                ('image', models.ImageField(upload_to='')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('file', models.FileField(db_index=True, upload_to='')),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('available', models.BooleanField(default=True, verbose_name='Доступен')),
                ('stock', models.PositiveIntegerField(verbose_name='На складе')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Category_fb')),
            ],
            options={
                'ordering': ['name'],
                'index_together': {('id', 'slug')},
            },
        ),
    ]
