# Generated by Django 2.2.10 on 2020-02-26 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_auto_20200226_1336'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category_fb',
            old_name='Категория fb account',
            new_name='Категория fb accaunt',
        ),
        migrations.RenameField(
            model_name='category_offer',
            old_name='Категория offers',
            new_name='Категория',
        ),
    ]
